from typing import Optional, List
from pydantic import BaseModel, Field
from .base_config import base_config
from .common import ProductType, ProductStatus

class SKUBase(BaseModel):
    name: str
    category: Optional[str] = None
    product_type: ProductType = ProductType.VOLUME
    units_per_carton: int = 1
    unit_size: float = 1000
    carton_size: float = 0
    hsn_code: str
    gst_percentage: float
    price_net_carton: float = 0
    price_gross_carton: float = 0
    price: float
    status: ProductStatus = ProductStatus.ACTIVE
    
    model_config = base_config

class SKU(SKUBase):
    id: str

class SKUCreate(SKUBase):
    id: str  # Generated by frontend initially?

class SchemeBase(BaseModel):
    description: str
    buy_sku_id: str = Field(alias="buySkuId")
    buy_quantity: int = Field(alias="buyQuantity")
    get_sku_id: str = Field(alias="getSkuId")
    get_quantity: int = Field(alias="getQuantity")
    start_date: str = Field(alias="startDate")
    end_date: str = Field(alias="endDate")
    is_global: bool = Field(default=False, alias="isGlobal")
    distributor_id: Optional[str] = Field(None, alias="distributorId")
    store_id: Optional[str] = Field(None, alias="storeId")
    
    model_config = base_config

class Scheme(SchemeBase):
    id: str
    stopped_by: Optional[str] = Field(None, alias="stoppedBy")
    stopped_date: Optional[str] = Field(None, alias="stoppedDate")

class SchemeCreate(SchemeBase):
    pass

class PriceTierBase(BaseModel):
    name: str
    description: str
    
    model_config = base_config

class PriceTier(PriceTierBase):
    id: str

class PriceTierCreate(PriceTierBase):
    pass

class PriceTierItem(BaseModel):
    tier_id: str = Field(alias="tierId")
    sku_id: str = Field(alias="skuId")
    price: float
    
    model_config = base_config
