import { createClient } from '@supabase/supabase-js';

// Prioritize environment variables
// FIX: Use process.env, which is populated by Vite's `define` config, to avoid issues with `import.meta.env` type definitions.
const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

// The generic type 'Database' will be generated by the Supabase CLI in a real project
// For now, we use 'any' to allow for dynamic queries.
export const supabase = (supabaseUrl && supabaseAnonKey)
  ? createClient<any>(supabaseUrl, supabaseAnonKey, {
      auth: {
        // Explicitly enable session persistence to ensure it works across page reloads,
        // especially in sandboxed or iframe environments.
        persistSession: true,
        // Automatically refresh the session token.
        autoRefreshToken: true,
        // Detect session from the URL, which is useful for OAuth and password recovery flows.
        detectSessionInUrl: true,
      },
    })
  : null;
